### ISSUE TITLE
Use alpha transparency for striping

### ISSUE THREAD

**Issue by lachlanjc** [tachyons-css/tachyons-tables#2]
Any reason not to use alpha transparency for table striping @mrmrs? On pages with non-white backgrounds it would look better (imo).

<img width="283" alt="screen shot 2016-09-01 at 1 19 25 pm" src="https://cloud.githubusercontent.com/assets/5074763/18177126/bc014c66-7046-11e6-8766-9bb88f17155b.png">
<img width="278" alt="screen shot 2016-09-01 at 1 21 41 pm" src="https://cloud.githubusercontent.com/assets/5074763/18177185/0b911d38-7047-11e6-831d-8c19644f02f3.png">

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
